
services:

  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: admin-painel
    container_name: mtg-ranked-manager
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: 'mtg-ranked-manager'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./database_data:/var/lib/mysql
    networks:
      - app-network
  ###< doctrine/doctrine-bundle ###

  nginx:
    image: nginx:1.25-alpine
    container_name: laravel-blog-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    networks:
      - app-network

  ### Adicionando o serviço Redis ###
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
    driver: local
  ###< doctrine/doctrine-bundle ###
